### PR TITLE
adds lambda function to schedule backups of datadog monitors and dash…

### PR DESCRIPTION
**Pull request by estib**
…boards to s3 bucket

#### Contribution Type

Script

#### Description

adds lambda function to schedule periodic backups of Datadog monitors and dashboards to an s3 bucket of choice. 

#### Value Add / Motivation

People make mistakes. It can help to have a backup of your dashboards and monitor configurations. 

#### Sources

N/A

#### Testing Strategy

I tested the function both for successful results and with a forced error (to ensure it created error events for alerting). [Screenshot here](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/geudZjXY/06108fa5-e4ab-444d-869f-a7df14768433.jpg?v=21f454f19c4f92a774c38e17e6511f45)

[The results in your s3 bucket look like this](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/xQuzZP2v/ff6ec789-2d25-4b31-a849-791ba81b9ade.jpg?v=2fbd16220aa7c49eca8b41274b91aeaf)

### CODE REVIEW

**Review by danielcbright — CHANGES_REQUESTED** [review]
Overall this is really awesome! The only thing I would recommend is that instead of having AWS featured on the main page, have a hyperlink for AWS Lambda, that way we can also add GCP Cloud Functions and Azure Functions equivalents later on for folks who aren't using AWS. Also, if we could add a to-do list to ensure that Azure and GCP are listed as future goals that would be awesome.

**Comment by estib** [comment]
good suggestions, i'll update

**Review by danielcbright — DISMISSED** [review]
LGTM! :shipit:

**Review by danielcbright — APPROVED** [review]
this is great, thanks for the screenshot as well, it will be really helpful for those setting it up!

**Review by danielcbright — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
